-- SQL script to seed 100 meals (70 Nigerian, 30 International)
INSERT INTO meals (id, name, category, price_min, price_max, prep_time_mins, dietary_tags, instructions) VALUES
-- Nigerian (70)
(gen_random_uuid(), 'Jollof Rice', 'Main', 2000, 2500, 60, '', 'Parboil rice, cook with tomato stew and spices.'),
(gen_random_uuid(), 'Egusi Soup', 'Main', 2000, 2500, 45, 'spicy', 'Whisk egusi into boiling meat stock with greens.'),
(gen_random_uuid(), 'Pounded Yam', 'Swallow', 1000, 1500, 30, 'gluten-free', 'Boil yam, then pound until smooth and elastic.'),
(gen_random_uuid(), 'Suya', 'Snack', 1000, 1500, 20, '', 'Rub beef slices with spicy peanut-based suya spice.'),
(gen_random_uuid(), 'Fried Plantain (Dodo)', 'Side', 800, 1300, 15, 'vegetarian', 'Slice ripe plantains and fry until golden brown.'),
(gen_random_uuid(), 'Ogbono Soup', 'Main', 2000, 2500, 40, 'spicy', 'Cook ground ogbono seeds in thick, savory stock.'),
(gen_random_uuid(), 'Efo Riro', 'Main', 2000, 2500, 35, 'spicy', 'Sauté spinach, locust beans, and meat in stew.'),
(gen_random_uuid(), 'Fried Rice', 'Main', 2000, 2500, 50, '', 'Stir-fry cooked rice with vegetables and light spices.'),
(gen_random_uuid(), 'Akara', 'Breakfast', 800, 1300, 25, 'vegetarian', 'Blend peeled beans, season, and fry dollops crisp.'),
(gen_random_uuid(), 'Moi Moi', 'Main', 2000, 2500, 60, '', 'Steam seasoned bean paste in banana leaves/containers.'),
(gen_random_uuid(), 'Pepper Soup', 'Main', 2000, 2500, 30, 'spicy', 'Simmer meat with intense local peppers and spices.'),
(gen_random_uuid(), 'Banga Soup', 'Main', 2000, 2500, 50, 'spicy', 'Boil palm nut extract with assorted fish/meat.'),
(gen_random_uuid(), 'Tuwo Shinkafa', 'Swallow', 1000, 1500, 35, 'gluten-free', 'Cook soft rice, then mash into smooth swallow.'),
(gen_random_uuid(), 'Amala', 'Swallow', 1000, 1500, 20, 'gluten-free', 'Mix yam flour into boiling water until smooth.'),
(gen_random_uuid(), 'Ewa Agoyin', 'Main', 2000, 2500, 90, '', 'Mash cooked beans, top with dark, spicy sauce.'),
(gen_random_uuid(), 'Asun', 'Snack', 1000, 1500, 30, '', 'Grill goat meat chunks with spicy pepper mix.'),
(gen_random_uuid(), 'Okra Soup', 'Main', 2000, 2500, 30, 'spicy', 'Cook chopped okra in broth with assorted proteins.'),
(gen_random_uuid(), 'Ofada Rice', 'Main', 2000, 2500, 45, 'spicy', 'Serve local rice with spicy locust bean stew.'),
(gen_random_uuid(), 'Meat Pie', 'Snack', 800, 1300, 40, '', 'Bake pastry filled with minced meat and veggies.'),
(gen_random_uuid(), 'Puff Puff', 'Snack', 500, 1000, 20, 'vegetarian', 'Deep-fry balls of sweetened dough until light brown.'),
(gen_random_uuid(), 'Yam Porridge', 'Main', 2000, 2500, 40, '', 'Simmer yam chunks with palm oil and veggies.'),
(gen_random_uuid(), 'Chin Chin', 'Snack', 500, 1000, 25, 'vegetarian', 'Deep-fry small, crunchy pieces of spiced dough.'),
(gen_random_uuid(), 'Boli', 'Snack', 500, 1000, 15, 'vegetarian', 'Roast ripe or unripe plantain over open fire.'),
(gen_random_uuid(), 'Fish Stew', 'Main', 2000, 2500, 35, 'spicy', 'Simmer fish in tomato-pepper base with spices.'),
(gen_random_uuid(), 'Chicken Stew', 'Main', 2000, 2500, 40, 'spicy', 'Simmer chicken in tomato-pepper base until tender.'),
(gen_random_uuid(), 'Beef Stew', 'Main', 2000, 2500, 45, 'spicy', 'Slow-cook beef in rich tomato-pepper sauce base.'),
(gen_random_uuid(), 'Vegetable Soup', 'Main', 2000, 2500, 30, 'spicy', 'Sauté chopped local greens in savory, spiced oil.'),
(gen_random_uuid(), 'Edikang Ikong', 'Main', 2500, 3500, 45, 'spicy', 'Cook pumpkin leaves and waterleaf with rich stock.'),
(gen_random_uuid(), 'Afang Soup', 'Main', 2500, 3500, 45, 'spicy', 'Cook afang leaves and waterleaf with palm oil.'),
(gen_random_uuid(), 'Bitterleaf Soup', 'Main', 2500, 3500, 40, 'spicy', 'Cook washed bitterleaf with protein and palm oil.'),
(gen_random_uuid(), 'Oha Soup', 'Main', 2500, 3500, 45, 'spicy', 'Simmer oha leaves with thick, seasoned soup base.'),
(gen_random_uuid(), 'Groundnut Soup', 'Main', 2500, 3500, 50, 'spicy', 'Cook meat/fish in rich, creamy peanut paste base.'),
(gen_random_uuid(), 'Peppered Snails', 'Snack', 1500, 2000, 30, 'spicy', 'Sauté cleaned snails in very spicy pepper sauce.'),
(gen_random_uuid(), 'Scotch Egg', 'Snack', 800, 1300, 30, '', 'Wrap boiled egg in sausage, coat, then fry.'),
(gen_random_uuid(), 'Egg Roll', 'Snack', 800, 1300, 30, 'vegetarian', 'Wrap boiled egg in flour dough and fry.'),
(gen_random_uuid(), 'Fried Yam', 'Side', 800, 1300, 15, 'vegetarian', 'Slice yam, season, and fry until crisp outside.'),
(gen_random_uuid(), 'Roasted Corn', 'Snack', 500, 1000, 10, 'vegetarian', 'Roast fresh corn cobs directly over hot coals.'),
(gen_random_uuid(), 'Boiled Corn', 'Snack', 500, 1000, 15, 'vegetarian', 'Boil fresh corn cobs until tender and sweet.'),
(gen_random_uuid(), 'Plantain Chips', 'Snack', 500, 1000, 10, 'vegetarian', 'Slice green plantains thin, fry until crunchy crisp.'),
(gen_random_uuid(), 'Egg Sauce', 'Breakfast', 1000, 1500, 15, 'vegetarian', 'Sauté onions/peppers, scramble eggs into the mix.'),
(gen_random_uuid(), 'Bread and Fried Egg', 'Breakfast', 1000, 1500, 10, 'vegetarian', 'Serve crispy fried egg inside sliced white bread.'),
(gen_random_uuid(), 'Semovita', 'Swallow', 1000, 1500, 15, 'gluten-free', 'Whisk semovita into boiling water until thick swallow.'),
(gen_random_uuid(), 'Wheat Flour Swallow', 'Swallow', 1000, 1500, 15, 'gluten-free', 'Whisk wheat flour into boiling water until thick.'),
(gen_random_uuid(), 'Garri', 'Swallow', 500, 1000, 5, 'gluten-free', 'Whisk garri into hot water for quick swallow.'),
(gen_random_uuid(), 'Fufu', 'Swallow', 1000, 1500, 40, 'gluten-free', 'Boil cassava/plantain, pound until very smooth texture.'),
(gen_random_uuid(), 'Eba', 'Swallow', 500, 1000, 10, 'gluten-free', 'Whisk garri into boiling water for elastic swallow.'),
(gen_random_uuid(), 'Coconut Rice', 'Main', 2000, 2500, 50, '', 'Cook rice in creamy coconut milk and spices.'),
(gen_random_uuid(), 'Beans and Plantain', 'Main', 2000, 2500, 45, 'vegetarian', 'Serve stewed beans with fried sweet ripe plantain.'),
(gen_random_uuid(), 'Porridge Beans', 'Main', 2000, 2500, 50, 'vegetarian', 'Simmer beans with palm oil, onions, and spices.'),
(gen_random_uuid(), 'Spaghetti Jollof', 'Main', 2000, 2500, 30, 'spicy', 'Cook spaghetti in rich tomato and pepper stew.'),
(gen_random_uuid(), 'Indomie', 'Breakfast', 800, 1300, 10, 'vegetarian', 'Boil noodles, add seasoning packet, stir-fry veggies.'),
(gen_random_uuid(), 'Yam and Egg Sauce', 'Breakfast', 1200, 1700, 30, 'vegetarian', 'Boil yam, serve with savory onion egg sauce.'),
(gen_random_uuid(), 'Akara and Bread', 'Breakfast', 1200, 1700, 25, 'vegetarian', 'Stuff crispy akara balls inside soft white bread.'),
(gen_random_uuid(), 'Tea and Bread', 'Breakfast', 500, 1000, 5, 'vegetarian', 'Brew hot tea, serve with sliced buttered bread.'),
(gen_random_uuid(), 'Custard and Akara', 'Breakfast', 1200, 1700, 15, 'vegetarian', 'Serve warm creamy custard with crispy akara balls.'),
(gen_random_uuid(), 'Pap (Ogi)', 'Breakfast', 800, 1300, 20, 'vegetarian', 'Mix fermented corn paste with boiling hot water.'),
(gen_random_uuid(), 'Fried Titus Fish', 'Side', 1200, 1700, 20, '', 'Season Titus fish well and deep-fry until crispy.'),
(gen_random_uuid(), 'Grilled Catfish', 'Main', 2500, 3500, 40, '', 'Marinate catfish, grill until smoky and well cooked.'),
(gen_random_uuid(), 'Cowleg Pepper Soup', 'Main', 3000, 4000, 60, 'spicy', 'Slow-cook cowleg in spicy, herbal broth base.'),
(gen_random_uuid(), 'Goat Meat Pepper Soup', 'Main', 2500, 3500, 45, 'spicy', 'Simmer goat meat in intense spicy broth base.'),
(gen_random_uuid(), 'Chicken Pepper Soup', 'Main', 2500, 3500, 35, 'spicy', 'Simmer chicken in spicy, aromatic herbal broth base.'),
(gen_random_uuid(), 'Nkwobi', 'Snack', 1500, 2000, 50, '', 'Mix cow parts in spicy, seasoned palm oil.'),
(gen_random_uuid(), 'Isi Ewu', 'Snack', 1500, 2000, 60, '', 'Mix goat head parts in spicy palm sauce.'),
(gen_random_uuid(), 'Abacha', 'Main', 1500, 2000, 30, 'spicy', 'Toss shredded cassava with spicy oil and ugba.'),
(gen_random_uuid(), 'Ugba', 'Snack', 1000, 1500, 30, '', 'Mix oil bean seeds with spicy, tasty sauce.'),
(gen_random_uuid(), 'Okpa', 'Main', 1500, 2000, 50, 'vegetarian', 'Steam seasoned bambara nut paste in leaves/pouches.'),
(gen_random_uuid(), 'Tuwo Masara', 'Swallow', 1000, 1500, 30, 'gluten-free', 'Whisk corn flour into boiling water for swallow.'),
(gen_random_uuid(), 'Miyan Kuka', 'Main', 2000, 2500, 40, 'spicy', 'Cook baobab leaf powder into thick, spicy soup.'),
(gen_random_uuid(), 'Miyan Tuwo', 'Main', 2000, 2500, 40, 'spicy', 'Cook rice with savory, spicy meat broth base.'),
(gen_random_uuid(), 'Kilishi', 'Snack', 1500, 2000, 120, '', 'Dry-cure thin beef slices with spicy seasoning mix.'),
-- International (30)
(gen_random_uuid(), 'Pasta Carbonara', 'Main', 2000, 3000, 30, '', 'Toss pasta with eggs, cheese, and fried pancetta.'),
(gen_random_uuid(), 'Pizza Margherita', 'Main', 2000, 3000, 45, 'vegetarian', 'Top dough with tomato, mozzarella, and fresh basil.'),
(gen_random_uuid(), 'Beef Burger', 'Main', 2000, 3000, 25, '', 'Grill beef patty, serve in bun with toppings.'),
(gen_random_uuid(), 'Caesar Salad', 'Side', 1000, 1500, 15, 'vegetarian', 'Toss romaine with dressing, croutons, and parmesan.'),
(gen_random_uuid(), 'Sushi Roll', 'Main', 2500, 3500, 40, '', 'Roll seasoned rice and fish in nori seaweed.'),
(gen_random_uuid(), 'Chicken Curry', 'Main', 2000, 3000, 40, 'spicy', 'Simmer chicken chunks in aromatic spiced curry sauce.'),
(gen_random_uuid(), 'Tacos', 'Main', 1500, 2500, 30, '', 'Fill tortilla with seasoned meat and fresh toppings.'),
(gen_random_uuid(), 'Grilled Salmon', 'Main', 3000, 4000, 35, '', 'Sear salmon fillet, serve with herbs and lemon.'),
(gen_random_uuid(), 'Vegetable Stir-fry', 'Main', 1500, 2500, 20, 'vegetarian', 'Quickly cook mixed vegetables with soy sauce base.'),
(gen_random_uuid(), 'Pancakes', 'Breakfast', 1000, 1500, 20, 'vegetarian', 'Cook thin, fluffy batter circles on hot griddle.'),
(gen_random_uuid(), 'French Toast', 'Breakfast', 1000, 1500, 15, 'vegetarian', 'Dip bread in egg-milk, fry until golden brown.'),
(gen_random_uuid(), 'Mashed Potatoes', 'Side', 800, 1300, 25, 'vegetarian', 'Boil potatoes, mash with butter and warm milk.'),
(gen_random_uuid(), 'Greek Salad', 'Side', 1000, 1500, 15, 'vegetarian', 'Toss cucumber, tomato, feta, olives, and dressing.'),
(gen_random_uuid(), 'Lasagna', 'Main', 2500, 3500, 60, '', 'Layer pasta with meat sauce, béchamel, and cheese.'),
(gen_random_uuid(), 'Chicken Wings', 'Snack', 1500, 2000, 25, 'spicy', 'Fry or bake wings, toss in savory sauce.'),
(gen_random_uuid(), 'Fish and Chips', 'Main', 2000, 3000, 40, '', 'Deep-fry battered fish, serve with potato fries.'),
(gen_random_uuid(), 'Ramen', 'Main', 2000, 3000, 40, 'spicy', 'Boil noodles in savory broth with meat toppings.'),
(gen_random_uuid(), 'Burrito', 'Main', 2000, 3000, 35, '', 'Wrap rice, beans, meat in large flour tortilla.'),
(gen_random_uuid(), 'Fried Rice (Chinese)', 'Main', 2000, 3000, 30, '', 'Stir-fry rice with egg, veggies, and soy sauce.'),
(gen_random_uuid(), 'Omelette', 'Breakfast', 800, 1300, 10, 'vegetarian', 'Whisk eggs, cook folded with preferred savory fillings.'),
(gen_random_uuid(), 'Sandwich', 'Breakfast', 800, 1300, 10, '', 'Layer meat, cheese, veggies between two bread slices.'),
(gen_random_uuid(), 'Chili Con Carne', 'Main', 2000, 3000, 50, 'spicy', 'Simmer ground beef with beans and spicy tomatoes.'),
(gen_random_uuid(), 'Pad Thai', 'Main', 2000, 3000, 30, '', 'Stir-fry noodles with egg, peanuts, and tamarind.'),
(gen_random_uuid(), 'Falafel', 'Snack', 1000, 1500, 30, 'vegetarian', 'Deep-fry spiced ground chickpea balls until crispy.'),
(gen_random_uuid(), 'Hummus', 'Snack', 800, 1300, 10, 'vegetarian', 'Blend chickpeas with tahini, lemon, and garlic.'),
(gen_random_uuid(), 'Tiramisu', 'Dessert', 1500, 2000, 30, 'vegetarian', 'Layer coffee-dipped ladyfingers with creamy mascarpone mix.'),
(gen_random_uuid(), 'Brownies', 'Dessert', 1200, 1700, 40, 'vegetarian', 'Bake rich, dense chocolate squares until just firm.'),
(gen_random_uuid(), 'Apple Pie', 'Dessert', 1500, 2000, 60, 'vegetarian', 'Bake spiced apple filling inside buttery pastry crust.'),
(gen_random_uuid(), 'Fruit Smoothie', 'Snack', 800, 1300, 5, 'vegetarian', 'Blend mixed fruits with yogurt until creamy smooth.'),
(gen_random_uuid(), 'Steak and Fries', 'Main', 3000, 4000, 35, '', 'Sear seasoned steak, serve with crispy potato fries.');
