-- SQL script to seed 200 meals (140 Nigerian, 60 International)
INSERT INTO meals (id, name, category, price_min, price_max, prep_time_mins, dietary_tags, cuisine, instructions) VALUES
-- Nigerian Mains (50)
(gen_random_uuid(), 'Jollof Rice', 'Main', 2000, 2500, 60, '', 'Nigerian', 'Parboil rice, cook with tomato stew and spices.'),
(gen_random_uuid(), 'Egusi Soup', 'Main', 2000, 2500, 45, 'spicy', 'Nigerian', 'Whisk egusi into boiling meat stock with greens.'),
(gen_random_uuid(), 'Ogbono Soup', 'Main', 2000, 2500, 40, 'spicy', 'Nigerian', 'Cook ground ogbono seeds in thick, savory stock.'),
(gen_random_uuid(), 'Efo Riro', 'Main', 2000, 2500, 35, 'spicy', 'Nigerian', 'Sauté spinach, locust beans, and meat in stew.'),
(gen_random_uuid(), 'Fried Rice', 'Main', 2000, 2500, 50, '', 'Nigerian', 'Stir-fry cooked rice with vegetables and light spices.'),
(gen_random_uuid(), 'Moi Moi', 'Main', 2000, 2500, 60, '', 'Nigerian', 'Steam seasoned bean paste in banana leaves or containers.'),
(gen_random_uuid(), 'Pepper Soup', 'Main', 2000, 2500, 30, 'spicy', 'Nigerian', 'Simmer meat with intense local peppers and spices.'),
(gen_random_uuid(), 'Banga Soup', 'Main', 2000, 2500, 50, 'spicy', 'Nigerian', 'Boil palm nut extract with assorted fish and meat.'),
(gen_random_uuid(), 'Ewa Agoyin', 'Main', 2000, 2500, 90, '', 'Nigerian', 'Mash cooked beans, top with dark, spicy sauce.'),
(gen_random_uuid(), 'Okra Soup', 'Main', 2000, 2500, 30, 'spicy', 'Nigerian', 'Cook chopped okra in broth with assorted proteins.'),
(gen_random_uuid(), 'Ofada Rice', 'Main', 2000, 2500, 45, 'spicy', 'Nigerian', 'Serve local rice with spicy locust bean stew.'),
(gen_random_uuid(), 'Yam Porridge', 'Main', 2000, 2500, 40, '', 'Nigerian', 'Simmer yam chunks with palm oil and veggies.'),
(gen_random_uuid(), 'Fish Stew', 'Main', 2000, 2500, 35, 'spicy', 'Nigerian', 'Simmer fish in tomato-pepper base with spices.'),
(gen_random_uuid(), 'Chicken Stew', 'Main', 2000, 2500, 40, 'spicy', 'Nigerian', 'Simmer chicken in tomato-pepper base until tender.'),
(gen_random_uuid(), 'Beef Stew', 'Main', 2000, 2500, 45, 'spicy', 'Nigerian', 'Slow-cook beef in rich tomato-pepper sauce base.'),
(gen_random_uuid(), 'Vegetable Soup', 'Main', 2000, 2500, 30, 'spicy', 'Nigerian', 'Sauté chopped local greens in savory, spiced oil.'),
(gen_random_uuid(), 'Edikang Ikong', 'Main', 2500, 3500, 45, 'spicy', 'Nigerian', 'Cook pumpkin leaves and waterleaf with rich stock.'),
(gen_random_uuid(), 'Afang Soup', 'Main', 2500, 3500, 45, 'spicy', 'Nigerian', 'Cook afang leaves and waterleaf with palm oil.'),
(gen_random_uuid(), 'Bitterleaf Soup', 'Main', 2500, 3500, 40, 'spicy', 'Nigerian', 'Cook washed bitterleaf with protein and palm oil.'),
(gen_random_uuid(), 'Oha Soup', 'Main', 2500, 3500, 45, 'spicy', 'Nigerian', 'Simmer oha leaves with thick, seasoned soup base.'),
(gen_random_uuid(), 'Groundnut Soup', 'Main', 2500, 3500, 50, 'spicy', 'Nigerian', 'Cook meat or fish in rich, creamy peanut paste.'),
(gen_random_uuid(), 'Nsala Soup', 'Main', 2500, 3500, 40, 'spicy', 'Nigerian', 'Cook white soup with yam, catfish, and uziza leaves.'),
(gen_random_uuid(), 'Ukodo', 'Main', 2000, 2500, 50, '', 'Nigerian', 'Simmer unripe plantain with yam and meat in pepper broth.'),
(gen_random_uuid(), 'Gbegiri', 'Main', 1500, 2000, 60, 'vegetarian', 'Nigerian', 'Cook and mash brown beans into smooth, savory porridge.'),
(gen_random_uuid(), 'Ewedu', 'Main', 1500, 2000, 25, 'spicy', 'Nigerian', 'Cook and mash jute leaves into a smooth, slimy soup.'),
(gen_random_uuid(), 'Miyan Kuka', 'Main', 2000, 2500, 40, 'spicy', 'Nigerian', 'Cook baobab leaf powder into thick, spicy soup.'),
(gen_random_uuid(), 'Miyan Taushe', 'Main', 2000, 3000, 45, 'spicy', 'Nigerian', 'Cook pumpkin with groundnut and meat in rich sauce.'),
(gen_random_uuid(), 'Dan Wake', 'Main', 1500, 2000, 35, 'spicy', 'Nigerian', 'Coat bean dumplings in ground pepper and oil.'),
(gen_random_uuid(), 'Ayamase', 'Main', 2500, 3500, 55, 'spicy', 'Nigerian', 'Cook ofada stew with green peppers and assorted meats.'),
(gen_random_uuid(), 'Miyan Gyada', 'Main', 2000, 2500, 40, 'spicy', 'Nigerian', 'Simmer groundnut paste with meat and local spices.'),
(gen_random_uuid(), 'Karkashi Soup', 'Main', 2000, 2500, 35, 'spicy', 'Nigerian', 'Cook sesame leaf with rich stock and proteins.'),
(gen_random_uuid(), 'Editan Soup', 'Main', 2500, 3500, 50, 'spicy', 'Nigerian', 'Cook editan leaves with assorted meat and fish.'),
(gen_random_uuid(), 'Alale Soup', 'Main', 2000, 2500, 40, 'spicy', 'Nigerian', 'Simmer beniseed paste with leafy greens and meat.'),
(gen_random_uuid(), 'Coconut Rice', 'Main', 2000, 2500, 50, 'gluten-free', 'Nigerian', 'Cook rice in creamy coconut milk and spices.'),
(gen_random_uuid(), 'Beans and Plantain', 'Main', 2000, 2500, 45, 'vegetarian', 'Nigerian', 'Serve stewed beans with fried sweet ripe plantain.'),
(gen_random_uuid(), 'Porridge Beans', 'Main', 2000, 2500, 50, 'vegetarian', 'Nigerian', 'Simmer beans with palm oil, onions, and spices.'),
(gen_random_uuid(), 'Spaghetti Jollof', 'Main', 2000, 2500, 30, 'spicy', 'Nigerian', 'Cook spaghetti in rich tomato and pepper stew.'),
(gen_random_uuid(), 'Grilled Catfish', 'Main', 2500, 3500, 40, '', 'Nigerian', 'Marinate catfish, grill until smoky and well cooked.'),
(gen_random_uuid(), 'Cowleg Pepper Soup', 'Main', 3000, 4000, 60, 'spicy', 'Nigerian', 'Slow-cook cowleg in spicy, herbal broth base.'),
(gen_random_uuid(), 'Goat Meat Pepper Soup', 'Main', 2500, 3500, 45, 'spicy', 'Nigerian', 'Simmer goat meat in intense spicy broth base.'),
(gen_random_uuid(), 'Chicken Pepper Soup', 'Main', 2500, 3500, 35, 'spicy', 'Nigerian', 'Simmer chicken in spicy, aromatic herbal broth.'),
(gen_random_uuid(), 'Abacha', 'Main', 1500, 2000, 30, 'spicy', 'Nigerian', 'Toss shredded cassava with spicy oil and ugba.'),
(gen_random_uuid(), 'Okpa', 'Main', 1500, 2000, 50, 'vegetarian', 'Nigerian', 'Steam seasoned bambara nut paste in leaves.'),
(gen_random_uuid(), 'Native Jollof Rice', 'Main', 2000, 3000, 55, 'spicy', 'Nigerian', 'Cook rice with smoked fish, periwinkle, and native spices.'),
(gen_random_uuid(), 'Yam Balls', 'Main', 1500, 2000, 30, 'vegetarian', 'Nigerian', 'Mash yam, shape into balls, and deep-fry until golden.'),
(gen_random_uuid(), 'Dambun Nama', 'Main', 2000, 3000, 90, 'spicy', 'Nigerian', 'Shred sun-dried beef and season with local spices.'),
(gen_random_uuid(), 'Mushroom Sauce', 'Main', 2000, 2500, 25, 'vegetarian', 'Nigerian', 'Sauté mushrooms in palm oil with local herbs.'),
(gen_random_uuid(), 'Tuwon Dawa Sauce', 'Main', 2000, 2500, 40, 'spicy', 'Nigerian', 'Prepare baobab or okra soup served with millet swallow.'),
(gen_random_uuid(), 'Waina', 'Main', 1500, 2000, 35, 'vegetarian', 'Nigerian', 'Steam fermented rice batter in round molds.'),
(gen_random_uuid(), 'Zogale', 'Main', 1500, 2000, 25, 'vegetarian', 'Nigerian', 'Sauté moringa leaves with groundnuts and spices.'),
-- Nigerian Swallows (11)
(gen_random_uuid(), 'Pounded Yam', 'Swallow', 1000, 1500, 30, 'gluten-free', 'Nigerian', 'Boil yam, then pound until smooth and elastic.'),
(gen_random_uuid(), 'Tuwo Shinkafa', 'Swallow', 1000, 1500, 35, 'gluten-free', 'Nigerian', 'Cook soft rice, then mash into smooth swallow.'),
(gen_random_uuid(), 'Amala', 'Swallow', 1000, 1500, 20, 'gluten-free', 'Nigerian', 'Mix yam flour into boiling water until smooth.'),
(gen_random_uuid(), 'Semovita', 'Swallow', 1000, 1500, 15, 'gluten-free', 'Nigerian', 'Whisk semovita into boiling water until thick.'),
(gen_random_uuid(), 'Wheat Flour Swallow', 'Swallow', 1000, 1500, 15, 'gluten-free', 'Nigerian', 'Whisk wheat flour into boiling water until thick.'),
(gen_random_uuid(), 'Garri', 'Swallow', 500, 1000, 5, 'gluten-free', 'Nigerian', 'Whisk garri into hot water for quick swallow.'),
(gen_random_uuid(), 'Fufu', 'Swallow', 1000, 1500, 40, 'gluten-free', 'Nigerian', 'Boil cassava and plantain, pound until smooth.'),
(gen_random_uuid(), 'Eba', 'Swallow', 500, 1000, 10, 'gluten-free', 'Nigerian', 'Whisk garri into boiling water for elastic swallow.'),
(gen_random_uuid(), 'Tuwo Masara', 'Swallow', 1000, 1500, 30, 'gluten-free', 'Nigerian', 'Whisk corn flour into boiling water for swallow.'),
(gen_random_uuid(), 'Lafun', 'Swallow', 1000, 1500, 20, 'gluten-free', 'Nigerian', 'Mix cassava flour into boiling water until smooth.'),
(gen_random_uuid(), 'Tuwo Dawa', 'Swallow', 1000, 1500, 35, 'gluten-free', 'Nigerian', 'Whisk millet flour into boiling water for swallow.'),
-- Nigerian Breakfasts (12)
(gen_random_uuid(), 'Akara', 'Breakfast', 800, 1300, 25, 'vegetarian', 'Nigerian', 'Blend peeled beans, season, and fry dollops crisp.'),
(gen_random_uuid(), 'Egg Sauce', 'Breakfast', 1000, 1500, 15, 'vegetarian', 'Nigerian', 'Sauté onions and peppers, scramble eggs into the mix.'),
(gen_random_uuid(), 'Bread and Fried Egg', 'Breakfast', 1000, 1500, 10, 'vegetarian', 'Nigerian', 'Serve crispy fried egg inside sliced white bread.'),
(gen_random_uuid(), 'Indomie', 'Breakfast', 800, 1300, 10, 'vegetarian', 'Nigerian', 'Boil noodles, add seasoning, stir-fry with veggies.'),
(gen_random_uuid(), 'Yam and Egg Sauce', 'Breakfast', 1200, 1700, 30, 'vegetarian', 'Nigerian', 'Boil yam, serve with savory onion egg sauce.'),
(gen_random_uuid(), 'Akara and Bread', 'Breakfast', 1200, 1700, 25, 'vegetarian', 'Nigerian', 'Stuff crispy akara balls inside soft white bread.'),
(gen_random_uuid(), 'Tea and Bread', 'Breakfast', 500, 1000, 5, 'vegetarian', 'Nigerian', 'Brew hot tea, serve with sliced buttered bread.'),
(gen_random_uuid(), 'Custard and Akara', 'Breakfast', 1200, 1700, 15, 'vegetarian', 'Nigerian', 'Serve warm creamy custard with crispy akara balls.'),
(gen_random_uuid(), 'Pap (Ogi)', 'Breakfast', 800, 1300, 20, 'vegetarian', 'Nigerian', 'Mix fermented corn paste with boiling hot water.'),
(gen_random_uuid(), 'Masa', 'Breakfast', 800, 1300, 30, 'gluten-free', 'Nigerian', 'Ferment rice batter, cook in round molds until golden.'),
(gen_random_uuid(), 'Koko and Koose', 'Breakfast', 800, 1300, 25, 'vegetarian', 'Nigerian', 'Serve millet porridge with crispy bean cakes.'),
(gen_random_uuid(), 'Alkubus', 'Breakfast', 800, 1300, 40, 'vegetarian', 'Nigerian', 'Steam fermented wheat dough into soft bread.'),
-- Nigerian Snacks (27)
(gen_random_uuid(), 'Suya', 'Snack', 1000, 1500, 20, 'spicy', 'Nigerian', 'Rub beef slices with spicy peanut-based suya spice.'),
(gen_random_uuid(), 'Asun', 'Snack', 1000, 1500, 30, 'spicy', 'Nigerian', 'Grill goat meat chunks with spicy pepper mix.'),
(gen_random_uuid(), 'Meat Pie', 'Snack', 800, 1300, 40, '', 'Nigerian', 'Bake pastry filled with minced meat and veggies.'),
(gen_random_uuid(), 'Puff Puff', 'Snack', 500, 1000, 20, 'vegetarian', 'Nigerian', 'Deep-fry balls of sweetened dough until light brown.'),
(gen_random_uuid(), 'Chin Chin', 'Snack', 500, 1000, 25, 'vegetarian', 'Nigerian', 'Deep-fry small, crunchy pieces of spiced dough.'),
(gen_random_uuid(), 'Boli', 'Snack', 500, 1000, 15, 'vegetarian', 'Nigerian', 'Roast ripe or unripe plantain over open fire.'),
(gen_random_uuid(), 'Peppered Snails', 'Snack', 1500, 2000, 30, 'spicy', 'Nigerian', 'Sauté cleaned snails in very spicy pepper sauce.'),
(gen_random_uuid(), 'Scotch Egg', 'Snack', 800, 1300, 30, '', 'Nigerian', 'Wrap boiled egg in sausage, coat, then fry.'),
(gen_random_uuid(), 'Egg Roll', 'Snack', 800, 1300, 30, 'vegetarian', 'Nigerian', 'Wrap boiled egg in flour dough and deep-fry.'),
(gen_random_uuid(), 'Nkwobi', 'Snack', 1500, 2000, 50, 'spicy', 'Nigerian', 'Mix cow parts in spicy, seasoned palm oil.'),
(gen_random_uuid(), 'Isi Ewu', 'Snack', 1500, 2000, 60, 'spicy', 'Nigerian', 'Mix goat head parts in spicy palm sauce.'),
(gen_random_uuid(), 'Ugba', 'Snack', 1000, 1500, 30, '', 'Nigerian', 'Mix oil bean seeds with spicy, tasty sauce.'),
(gen_random_uuid(), 'Kilishi', 'Snack', 1500, 2000, 120, 'spicy', 'Nigerian', 'Dry-cure thin beef slices with spicy seasoning mix.'),
(gen_random_uuid(), 'Kuli Kuli', 'Snack', 500, 1000, 30, 'vegetarian', 'Nigerian', 'Deep-fry groundnut paste into crispy sticks.'),
(gen_random_uuid(), 'Balangu', 'Snack', 1500, 2000, 40, 'spicy', 'Nigerian', 'Grill seasoned meat over open flame until smoky.'),
(gen_random_uuid(), 'Awara', 'Snack', 500, 1000, 20, 'vegetarian', 'Nigerian', 'Deep-fry soybean curd until golden and crispy.'),
(gen_random_uuid(), 'Gizdodo', 'Snack', 1500, 2000, 30, 'spicy', 'Nigerian', 'Sauté gizzards with fried plantain in pepper sauce.'),
(gen_random_uuid(), 'Fish Roll', 'Snack', 800, 1300, 35, '', 'Nigerian', 'Wrap seasoned fish in dough and deep-fry golden.'),
(gen_random_uuid(), 'Samosa', 'Snack', 800, 1300, 30, 'spicy', 'Nigerian', 'Fill pastry triangles with spiced meat and onions.'),
(gen_random_uuid(), 'Buns', 'Snack', 500, 1000, 20, 'vegetarian', 'Nigerian', 'Deep-fry sweetened flour dough balls until golden.'),
(gen_random_uuid(), 'Gizzard', 'Snack', 1200, 1700, 25, 'spicy', 'Nigerian', 'Sauté chicken gizzards in spicy pepper sauce.'),
(gen_random_uuid(), 'Roasted Corn', 'Snack', 500, 1000, 10, 'vegetarian', 'Nigerian', 'Roast fresh corn cobs directly over hot coals.'),
(gen_random_uuid(), 'Boiled Corn', 'Snack', 500, 1000, 15, 'vegetarian', 'Nigerian', 'Boil fresh corn cobs until tender and sweet.'),
(gen_random_uuid(), 'Plantain Chips', 'Snack', 500, 1000, 10, 'vegetarian', 'Nigerian', 'Slice green plantains thin, fry until crunchy.'),
(gen_random_uuid(), 'Coconut Candy', 'Snack', 500, 1000, 30, 'vegetarian', 'Nigerian', 'Boil grated coconut with sugar until caramelized.'),
(gen_random_uuid(), 'Groundnut Cake', 'Snack', 500, 1000, 20, 'vegetarian', 'Nigerian', 'Bind roasted groundnuts in caramelized sugar.'),
(gen_random_uuid(), 'Dankwa', 'Snack', 500, 1000, 15, 'vegetarian', 'Nigerian', 'Toast millet with groundnuts and spices.'),
-- Nigerian Sides (10)
(gen_random_uuid(), 'Fried Plantain (Dodo)', 'Side', 800, 1300, 15, 'vegetarian', 'Nigerian', 'Slice ripe plantains and fry until golden brown.'),
(gen_random_uuid(), 'Fried Yam', 'Side', 800, 1300, 15, 'vegetarian', 'Nigerian', 'Slice yam, season, and fry until crisp outside.'),
(gen_random_uuid(), 'Fried Titus Fish', 'Side', 1200, 1700, 20, '', 'Nigerian', 'Season Titus fish well and deep-fry until crispy.'),
(gen_random_uuid(), 'Nigerian Salad', 'Side', 1000, 1500, 15, 'vegetarian', 'Nigerian', 'Toss lettuce, tomato, cucumber with baked beans and eggs.'),
(gen_random_uuid(), 'Nigerian Coleslaw', 'Side', 800, 1300, 15, 'vegetarian', 'Nigerian', 'Shred cabbage and carrots with creamy mayonnaise.'),
(gen_random_uuid(), 'Boiled Plantain', 'Side', 500, 1000, 20, 'vegetarian', 'Nigerian', 'Boil peeled plantain until tender, serve with sauce.'),
(gen_random_uuid(), 'Steamed Vegetables', 'Side', 800, 1300, 15, 'vegetarian', 'Nigerian', 'Steam mixed local greens until tender and bright.'),
(gen_random_uuid(), 'Fried Chicken', 'Side', 1500, 2000, 25, '', 'Nigerian', 'Season chicken pieces and deep-fry until golden.'),
(gen_random_uuid(), 'Fried Fish', 'Side', 1500, 2000, 25, '', 'Nigerian', 'Season whole fish and deep-fry until crispy.'),
(gen_random_uuid(), 'Gizzard Sauce', 'Side', 1200, 1700, 25, 'spicy', 'Nigerian', 'Simmer diced gizzards in spicy pepper sauce.'),
-- Nigerian Desserts (6)
(gen_random_uuid(), 'Puff Puff with Honey', 'Dessert', 500, 1000, 20, 'vegetarian', 'Nigerian', 'Drizzle honey over golden, deep-fried dough balls.'),
(gen_random_uuid(), 'Coconut Rice Pudding', 'Dessert', 1000, 1500, 35, 'vegetarian', 'Nigerian', 'Simmer rice in coconut milk with sugar and spices.'),
(gen_random_uuid(), 'Fruit Salad', 'Dessert', 800, 1300, 10, 'vegetarian', 'Nigerian', 'Toss fresh seasonal fruits with light honey drizzle.'),
(gen_random_uuid(), 'Peppermint Candy', 'Dessert', 300, 500, 60, 'vegetarian', 'Nigerian', 'Boil sugar and peppermint extract, cool and break.'),
(gen_random_uuid(), 'Doughnuts', 'Dessert', 800, 1300, 30, 'vegetarian', 'Nigerian', 'Deep-fry sweet yeast dough rings until golden.'),
(gen_random_uuid(), 'Queen Cakes', 'Dessert', 800, 1300, 35, 'vegetarian', 'Nigerian', 'Bake small, sweet sponge cakes until light and fluffy.'),
-- Extra Nigerian mains (12)
(gen_random_uuid(), 'Pepper Rice', 'Main', 2000, 2500, 40, 'spicy', 'Nigerian', 'Cook rice with generous blend of peppers and spices.'),
(gen_random_uuid(), 'Coconut Jollof Rice', 'Main', 2000, 3000, 55, '', 'Nigerian', 'Cook jollof rice with rich coconut milk infusion.'),
(gen_random_uuid(), 'Yaji Fish', 'Main', 2000, 3000, 30, 'spicy', 'Nigerian', 'Grill fish coated in spicy yaji peanut rub.'),
(gen_random_uuid(), 'Fresh Fish Pepper Soup', 'Main', 2500, 3500, 35, 'spicy', 'Nigerian', 'Simmer fresh fish in spicy herbal pepper broth.'),
(gen_random_uuid(), 'Dry Fish Pepper Soup', 'Main', 2000, 2500, 30, 'spicy', 'Nigerian', 'Cook dried fish in aromatic spicy pepper broth.'),
(gen_random_uuid(), 'Bushmeat Pepper Soup', 'Main', 3000, 4000, 60, 'spicy', 'Nigerian', 'Slow-cook bushmeat in intense pepper soup spices.'),
(gen_random_uuid(), 'Catfish Stew', 'Main', 2500, 3500, 40, 'spicy', 'Nigerian', 'Simmer catfish chunks in rich tomato pepper sauce.'),
(gen_random_uuid(), 'Goat Meat Stew', 'Main', 2500, 3500, 50, 'spicy', 'Nigerian', 'Slow-cook goat meat in thick tomato pepper sauce.'),
(gen_random_uuid(), 'Turkey Pepper Soup', 'Main', 3000, 4000, 45, 'spicy', 'Nigerian', 'Simmer turkey pieces in spicy herbal broth base.'),
(gen_random_uuid(), 'Snail Pepper Soup', 'Main', 3000, 4000, 40, 'spicy', 'Nigerian', 'Cook snails in spicy aromatic pepper soup broth.'),
(gen_random_uuid(), 'Assorted Meat Stew', 'Main', 3000, 4000, 55, 'spicy', 'Nigerian', 'Simmer assorted meats in rich tomato pepper sauce.'),
(gen_random_uuid(), 'White Soup', 'Main', 2500, 3500, 45, 'spicy', 'Nigerian', 'Cook yam-thickened soup with catfish and uziza.'),
-- Extra Nigerian breakfasts (2)
(gen_random_uuid(), 'Yam and Palm Oil', 'Breakfast', 800, 1300, 20, 'vegetarian', 'Nigerian', 'Boil yam, serve with red palm oil and salt.'),
(gen_random_uuid(), 'Bread and Akara', 'Breakfast', 1200, 1700, 25, 'vegetarian', 'Nigerian', 'Serve crispy bean cakes between soft bread slices.'),
-- Extra Nigerian snacks (4)
(gen_random_uuid(), 'Agege Bread', 'Snack', 500, 1000, 10, 'vegetarian', 'Nigerian', 'Serve soft, fluffy Nigerian-style sweet bread loaf.'),
(gen_random_uuid(), 'Yaji Chips', 'Snack', 500, 1000, 15, 'vegetarian', 'Nigerian', 'Toss fried potato chips in spicy yaji seasoning.'),
(gen_random_uuid(), 'Roasted Groundnut', 'Snack', 300, 500, 10, 'vegetarian', 'Nigerian', 'Roast raw groundnuts until golden and crunchy.'),
(gen_random_uuid(), 'Coconut Flakes', 'Snack', 500, 1000, 15, 'vegetarian', 'Nigerian', 'Toast fresh coconut shavings until golden crisp.'),
-- Extra Nigerian sides (2)
(gen_random_uuid(), 'Sweet Potato Fries', 'Side', 800, 1300, 25, 'vegetarian', 'Nigerian', 'Season sweet potato strips and bake until crispy.'),
(gen_random_uuid(), 'Spicy Fried Potatoes', 'Side', 800, 1300, 20, 'vegetarian', 'Nigerian', 'Cube potatoes, season with pepper and fry.'),
-- Extra Nigerian desserts (2)
(gen_random_uuid(), 'Zobo Sorbet', 'Dessert', 800, 1300, 120, 'vegetarian', 'Nigerian', 'Freeze hibiscus tea blend into refreshing sorbet.'),
(gen_random_uuid(), 'Kunun Aya Pudding', 'Dessert', 800, 1300, 20, 'vegetarian', 'Nigerian', 'Thicken tiger nut milk with cornstarch and sweeten.'),
