-- SQL script to seed 100 meals (70 Nigerian, 30 International)
INSERT INTO meals (id, name, category, prep_time_mins) VALUES
-- Nigerian (70)
(gen_random_uuid(), 'Jollof Rice', 'Main', 60),
(gen_random_uuid(), 'Egusi Soup', 'Main', 45),
(gen_random_uuid(), 'Pounded Yam', 'Swallow', 30),
(gen_random_uuid(), 'Suya', 'Snack', 20),
(gen_random_uuid(), 'Fried Plantain (Dodo)', 'Side', 15),
(gen_random_uuid(), 'Ogbono Soup', 'Main', 40),
(gen_random_uuid(), 'Efo Riro', 'Main', 35),
(gen_random_uuid(), 'Fried Rice', 'Main', 50),
(gen_random_uuid(), 'Akara', 'Breakfast', 25),
(gen_random_uuid(), 'Moi Moi', 'Main', 60),
(gen_random_uuid(), 'Pepper Soup', 'Main', 30),
(gen_random_uuid(), 'Banga Soup', 'Main', 50),
(gen_random_uuid(), 'Tuwo Shinkafa', 'Swallow', 35),
(gen_random_uuid(), 'Amala', 'Swallow', 20),
(gen_random_uuid(), 'Ewa Agoyin', 'Main', 90),
(gen_random_uuid(), 'Asun', 'Snack', 30),
(gen_random_uuid(), 'Okra Soup', 'Main', 30),
(gen_random_uuid(), 'Ofada Rice', 'Main', 45),
(gen_random_uuid(), 'Meat Pie', 'Snack', 40),
(gen_random_uuid(), 'Puff Puff', 'Snack', 20),
(gen_random_uuid(), 'Yam Porridge', 'Main', 40),
(gen_random_uuid(), 'Chin Chin', 'Snack', 25),
(gen_random_uuid(), 'Boli', 'Snack', 15),
(gen_random_uuid(), 'Fish Stew', 'Main', 35),
(gen_random_uuid(), 'Chicken Stew', 'Main', 40),
(gen_random_uuid(), 'Beef Stew', 'Main', 45),
(gen_random_uuid(), 'Vegetable Soup', 'Main', 30),
(gen_random_uuid(), 'Edikang Ikong', 'Main', 45),
(gen_random_uuid(), 'Afang Soup', 'Main', 45),
(gen_random_uuid(), 'Bitterleaf Soup', 'Main', 40),
(gen_random_uuid(), 'Oha Soup', 'Main', 45),
(gen_random_uuid(), 'Groundnut Soup', 'Main', 50),
(gen_random_uuid(), 'Peppered Snails', 'Snack', 30),
(gen_random_uuid(), 'Scotch Egg', 'Snack', 30),
(gen_random_uuid(), 'Egg Roll', 'Snack', 30),
(gen_random_uuid(), 'Fried Yam', 'Side', 15),
(gen_random_uuid(), 'Roasted Corn', 'Snack', 10),
(gen_random_uuid(), 'Boiled Corn', 'Snack', 15),
(gen_random_uuid(), 'Plantain Chips', 'Snack', 10),
(gen_random_uuid(), 'Egg Sauce', 'Breakfast', 15),
(gen_random_uuid(), 'Bread and Fried Egg', 'Breakfast', 10),
(gen_random_uuid(), 'Semovita', 'Swallow', 15),
(gen_random_uuid(), 'Wheat Flour Swallow', 'Swallow', 15),
(gen_random_uuid(), 'Garri', 'Swallow', 5),
(gen_random_uuid(), 'Fufu', 'Swallow', 40),
(gen_random_uuid(), 'Eba', 'Swallow', 10),
(gen_random_uuid(), 'Coconut Rice', 'Main', 50),
(gen_random_uuid(), 'Beans and Plantain', 'Main', 45),
(gen_random_uuid(), 'Porridge Beans', 'Main', 50),
(gen_random_uuid(), 'Spaghetti Jollof', 'Main', 30),
(gen_random_uuid(), 'Indomie', 'Breakfast', 10),
(gen_random_uuid(), 'Yam and Egg Sauce', 'Breakfast', 30),
(gen_random_uuid(), 'Akara and Bread', 'Breakfast', 25),
(gen_random_uuid(), 'Tea and Bread', 'Breakfast', 5),
(gen_random_uuid(), 'Custard and Akara', 'Breakfast', 15),
(gen_random_uuid(), 'Pap (Ogi)', 'Breakfast', 20),
(gen_random_uuid(), 'Fried Titus Fish', 'Side', 20),
(gen_random_uuid(), 'Grilled Catfish', 'Main', 40),
(gen_random_uuid(), 'Cowleg Pepper Soup', 'Main', 60),
(gen_random_uuid(), 'Goat Meat Pepper Soup', 'Main', 45),
(gen_random_uuid(), 'Chicken Pepper Soup', 'Main', 35),
(gen_random_uuid(), 'Nkwobi', 'Snack', 50),
(gen_random_uuid(), 'Isi Ewu', 'Snack', 60),
(gen_random_uuid(), 'Abacha', 'Main', 30),
(gen_random_uuid(), 'Ugba', 'Snack', 30),
(gen_random_uuid(), 'Okpa', 'Main', 50),
(gen_random_uuid(), 'Tuwo Masara', 'Swallow', 30),
(gen_random_uuid(), 'Miyan Kuka', 'Main', 40),
(gen_random_uuid(), 'Miyan Tuwo', 'Main', 40),
(gen_random_uuid(), 'Kilishi', 'Snack', 120),
-- International (30)
(gen_random_uuid(), 'Pasta Carbonara', 'Main', 30),
(gen_random_uuid(), 'Pizza Margherita', 'Main', 45),
(gen_random_uuid(), 'Beef Burger', 'Main', 25),
(gen_random_uuid(), 'Caesar Salad', 'Side', 15),
(gen_random_uuid(), 'Sushi Roll', 'Main', 40),
(gen_random_uuid(), 'Chicken Curry', 'Main', 40),
(gen_random_uuid(), 'Tacos', 'Main', 30),
(gen_random_uuid(), 'Grilled Salmon', 'Main', 35),
(gen_random_uuid(), 'Vegetable Stir-fry', 'Main', 20),
(gen_random_uuid(), 'Pancakes', 'Breakfast', 20),
(gen_random_uuid(), 'French Toast', 'Breakfast', 15),
(gen_random_uuid(), 'Mashed Potatoes', 'Side', 25),
(gen_random_uuid(), 'Greek Salad', 'Side', 15),
(gen_random_uuid(), 'Lasagna', 'Main', 60),
(gen_random_uuid(), 'Chicken Wings', 'Snack', 25),
(gen_random_uuid(), 'Fish and Chips', 'Main', 40),
(gen_random_uuid(), 'Ramen', 'Main', 40),
(gen_random_uuid(), 'Burrito', 'Main', 35),
(gen_random_uuid(), 'Fried Rice (Chinese)', 'Main', 30),
(gen_random_uuid(), 'Omelette', 'Breakfast', 10),
(gen_random_uuid(), 'Sandwich', 'Breakfast', 10),
(gen_random_uuid(), 'Chili Con Carne', 'Main', 50),
(gen_random_uuid(), 'Pad Thai', 'Main', 30),
(gen_random_uuid(), 'Falafel', 'Snack', 30),
(gen_random_uuid(), 'Hummus', 'Snack', 10),
(gen_random_uuid(), 'Tiramisu', 'Dessert', 30),
(gen_random_uuid(), 'Brownies', 'Dessert', 40),
(gen_random_uuid(), 'Apple Pie', 'Dessert', 60),
(gen_random_uuid(), 'Fruit Smoothie', 'Snack', 5),
(gen_random_uuid(), 'Steak and Fries', 'Main', 35);

