import {
  BurgerIcon,
  CoffeeIcon,
  ForkAndKnife,
  SnackIcon,
  SpagIcon,
  UtensilsIcon,
} from "./icons";

export const WeekPlan = [
  {
    day: "Sunday",
    color: "bg-green-800",
    meals: [
      {
        slug: "bread-and-egg",
        type: "BREAKFAST",
        name: "Bread & Egg",
        description: "Soft bread served with lightly fried eggs.",
        ingredients: ["Bread", "Egg", "Vegetable Oil", "Salt"],
        price: "₦700",
        icon: <SnackIcon className="text-text-primary" />,
        image: "/images/bread_scrambled_egg.jpg",
        category: ["Proteins"],
      },
      {
        slug: "jollof-rice-and-grilled-fish",
        type: "LUNCH",
        name: "Jollof Rice & Grilled Fish",
        description: "Smoky jollof rice paired with seasoned grilled fish.",
        ingredients: [
          "Rice",
          "Tomatoes",
          "Pepper",
          "Onions",
          "Fish",
          "Vegetable Oil",
          "Seasoning Cubes",
          "Tomato Paste",
          "Curry Powder",
          "Thyme",
          "Salt",
        ],
        price: "₦1,600",
        icon: <BurgerIcon className="text-accent-orange" />,
        image: "/images/jollof_fish_plantains.png",
        category: ["Rice Dishes", "Proteins"],
      },
      {
        slug: "garri-and-groundnut",
        type: "DINNER",
        name: "Garri & Groundnut",
        description: "Simple soaked garri served with crunchy groundnuts.",
        ingredients: ["Garri", "Groundnut", "Sugar", "Water"],
        price: "₦400",
        icon: <ForkAndKnife className="text-text-primary" />,
        image: "/images/garri-and-groundnut.jpg",
        category: ["Swallows"],
      },
    ],
  },

  {
    day: "Monday",
    color: "bg-orange-800",
    meals: [
      {
        slug: "toast-and-tea",
        type: "BREAKFAST",
        name: "Toast & Tea",
        description: "Buttered toast with warm sweet tea.",
        ingredients: ["Bread", "Tea Leaves", "Sugar", "Milk", "Butter"],
        price: "₦600",
        icon: <CoffeeIcon className="text-text-primary" />,
        image: "/images/tea-bread-small-image.png",
        category: ["Proteins"],
      },
      {
        slug: "beans-and-fried-plantain",
        type: "LUNCH",
        name: "Beans & Fried Plantain",
        description: "Hearty beans served with sweet fried plantains.",
        ingredients: ["Beans", "Plantain", "Palm Oil", "Salt", "Onions", "Pepper"],
        price: "₦900",
        icon: <BurgerIcon className="text-accent-orange" />,
        image: "/images/plantain.jpg",
        category: ["Proteins"],
      },
      {
        slug: "indomie-and-egg",
        type: "DINNER",
        name: "Indomie & Egg",
        description: "Quick noodles tossed with scrambled eggs.",
        ingredients: ["Instant Noodles", "Egg", "Onions", "Vegetable Oil"],
        price: "₦700",
        icon: <SpagIcon className="text-text-primary" />,
        image: "/images/indomie-and-eggs.jpg",
        category: ["Proteins"],
      },
    ],
  },

  {
    day: "Tuesday",
    color: "bg-green-900",
    meals: [
      {
        slug: "pap-and-akara",
        type: "BREAKFAST",
        name: "Pap & Akara",
        description: "Smooth pap served with crispy bean cakes.",
        ingredients: ["Corn Flour", "Beans", "Palm Oil", "Onions", "Pepper", "Salt", "Sugar", "Milk"],
        price: "₦700",
        icon: <SnackIcon className="text-text-primary" />,
        image: "/images/pap-and-akara.webp",
        category: ["Swallows", "Proteins"],
      },
      {
        slug: "simple-beef-suya-and-bread",
        type: "LUNCH",
        name: "Beef Suya & Bread",
        description: "Spiced grilled beef suya served with fresh bread.",
        ingredients: ["Beef", "Suya Spice", "Bread", "Onions"],
        price: "₦1,100",
        icon: <UtensilsIcon className="text-accent-orange" />,
        image: "/images/beef_suya.png",
        category: ["Proteins"],
      },
      {
        slug: "rice-and-stew",
        type: "DINNER",
        name: "Rice & Stew",
        description: "Classic rice served with rich tomato stew.",
        ingredients: [
          "Rice",
          "Tomatoes",
          "Pepper",
          "Onions",
          "Vegetable Oil",
          "Seasoning Cubes",
          "Beef",
          "Tomato Paste",
          "Salt",
        ],
        price: "₦650",
        icon: <ForkAndKnife className="text-text-primary" />,
        image: "/images/rice-and-stew.jpg",
        category: ["Rice Dishes"],
      },
    ],
  },

  {
    day: "Wednesday",
    color: "bg-green-800",
    meals: [
      {
        slug: "bread-and-tea",
        type: "BREAKFAST",
        name: "Bread & Tea",
        description: "Light breakfast of bread and warm tea.",
        ingredients: ["Bread", "Tea Leaves", "Sugar", "Milk", "Butter"],
        price: "₦500",
        icon: <CoffeeIcon className="text-text-primary" />,
        image: "/images/tea-bread-small-image.png",
        category: ["Proteins"],
      },
      {
        slug: "egusi-and-pounded-yam",
        type: "LUNCH",
        name: "Egusi & Pounded Yam",
        description: "Rich melon soup served with soft pounded yam.",
        ingredients: [
          "Melon Seeds",
          "Yam",
          "Spinach",
          "Palm Oil",
          "Crayfish",
          "Pepper",
          "Onions",
          "Seasoning Cubes",
          "Salt",
          "Beef",
        ],
        price: "₦1,400",
        icon: <UtensilsIcon className="text-accent-orange" />,
        image: "/images/swallow_egusi.png",
        category: ["Swallows", "Soups"],
      },
      {
        slug: "fried-yam-and-egg-sauce",
        type: "DINNER",
        name: "Fried Yam & Egg Sauce",
        description: "Crispy fried yam served with spicy egg sauce.",
        ingredients: [
          "Yam",
          "Egg",
          "Tomatoes",
          "Pepper",
          "Onions",
          "Vegetable Oil",
          "Salt",
        ],
        price: "₦900",
        icon: <ForkAndKnife className="text-text-primary" />,
        image: "/images/fried-yam-and-egg-sauce.jpg",
        category: ["Proteins"],
      },
    ],
  },

  {
    day: "Thursday",
    color: "bg-orange-900",
    meals: [
      {
        slug: "moi-moi-and-custard",
        type: "BREAKFAST",
        name: "Moi Moi & Custard",
        description: "Steamed bean pudding served with sweet custard.",
        ingredients: ["Beans", "Corn Flour", "Sugar", "Milk", "Palm Oil", "Onions", "Pepper", "Crayfish", "Salt"],
        price: "₦800",
        icon: <SnackIcon className="text-text-primary" />,
        image: "/images/moimoi-and-custard.jpg",
        category: ["Proteins"],
      },
      {
        slug: "amala-and-ewedu",
        type: "LUNCH",
        name: "Amala & Ewedu",
        description: "Soft amala served with jute leaf soup.",
        ingredients: [
          "Yam Flour",
          "Jute Leaves",
          "Locust Beans",
          "Crayfish",
          "Pepper",
          "Beef",
          "Seasoning Cubes",
          "Salt",
        ],
        price: "₦1,500",
        icon: <UtensilsIcon className="text-accent-orange" />,
        image: "/images/Amala_ewedu_and_assorted_meat.jpg",
        category: ["Swallows", "Soups"],
      },
      {
        slug: "grilled-chicken-and-fries",
        type: "DINNER",
        name: "Grilled Chicken & Fries",
        description: "Grilled chicken served with crispy potato fries.",
        ingredients: ["Chicken", "Potatoes", "Vegetable Oil", "Spices", "Salt", "Onions", "Pepper"],
        price: "₦1,800",
        icon: <BurgerIcon className="text-text-primary" />,
        image: "/images/grilled-chicken-and-chips.jpg",
        category: ["Proteins"],
      },
    ],
  },

  {
    day: "Friday",
    color: "bg-green-700",
    meals: [
      {
        slug: "akara-and-ogi",
        type: "BREAKFAST",
        name: "Akara & Ogi",
        description: "Crispy bean cakes served with smooth pap.",
        ingredients: ["Beans", "Corn Flour", "Palm Oil", "Sugar", "Onions", "Pepper", "Salt", "Milk"],
        price: "₦600",
        icon: <SnackIcon className="text-text-primary" />,
        image: "/images/pap-and-akara.webp",
        category: ["Proteins"],
      },
      {
        slug: "eba-and-okra-soup",
        type: "LUNCH",
        name: "Eba & Okra Soup",
        description: "Cassava swallow served with okra soup.",
        ingredients: [
          "Cassava Flour",
          "Okra",
          "Palm Oil",
          "Crayfish",
          "Fish",
          "Pepper",
          "Salt",
          "Seasoning Cubes",
          "Locust Beans",
          "Beef",
        ],
        price: "₦1,300",
        icon: <UtensilsIcon className="text-accent-orange" />,
        image: "/images/okra.jpg",
        category: ["Swallows", "Soups"],
      },
      {
        slug: "suya-and-cold-zobo",
        type: "DINNER",
        name: "Suya & Zobo",
        description: "Spiced beef suya served with chilled hibiscus drink.",
        ingredients: [
          "Beef",
          "Suya Spice",
          "Hibiscus Leaves",
          "Ginger",
          "Sugar",
        ],
        price: "₦1,200",
        icon: <ForkAndKnife className="text-text-primary" />,
        image: "/images/beef_suya.png",
        category: ["Proteins"],
      },
    ],
  },

  {
    day: "Saturday",
    color: "bg-orange-700",
    meals: [
      {
        slug: "pancakes-and-coffee",
        type: "BREAKFAST",
        name: "Pancakes & Coffee",
        description: "Fluffy pancakes served with hot coffee.",
        ingredients: [
          "Flour",
          "Egg",
          "Milk",
          "Sugar",
          "Butter",
          "Coffee Beans",
          "Baking Powder",
          "Salt",
        ],
        price: "₦1,000",
        icon: <CoffeeIcon className="text-text-primary" />,
        image: "/images/pancakes-and-coffee.jpg",
        category: ["Proteins"],
      },
      {
        slug: "native-rice-and-ponmo",
        type: "LUNCH",
        name: "Native Rice & Ponmo",
        description: "Local rice cooked with cow skin and spices.",
        ingredients: [
          "Rice",
          "Cow Skin",
          "Palm Oil",
          "Pepper",
          "Onions",
          "Seasoning Cubes",
          "Locust Beans",
          "Crayfish",
          "Salt",
        ],
        price: "₦1,100",
        icon: <BurgerIcon className="text-accent-orange" />,
        image: "/images/ofada-and-ponmo.jpg",
        category: ["Rice Dishes", "Proteins"],
      },
      {
        slug: "fish-pepper-soup",
        type: "DINNER",
        name: "Fish Pepper Soup",
        description: "Light spicy fish soup with aromatic herbs.",
        ingredients: ["Fish", "Pepper", "Ginger", "Garlic", "Scent Leaves", "Seasoning Cubes", "Salt", "Onions"],
        price: "₦1,500",
        icon: <SpagIcon className="text-text-primary" />,
        image: "/images/fisherman_soup.png",
        category: ["Soups", "Proteins"],
      },
    ],
  },
];
