import { BurgerIcon, ForkAndKnife, SnackIcon, UtensilsIcon } from "./icons";

const DAY_COLORS = {
  Monday: "bg-orange-800",
  Tuesday: "bg-green-900",
  Wednesday: "bg-green-800",
  Thursday: "bg-orange-900",
  Friday: "bg-green-700",
  Saturday: "bg-orange-700",
  Sunday: "bg-green-800",
};

const SLOT_ICONS = {
  Breakfast: <SnackIcon className="text-text-primary" />,
  Lunch: <BurgerIcon className="text-accent-orange" />,
  Dinner: <ForkAndKnife className="text-text-primary" />,
};

// Maps a meal name (from the DB) to a local public image path.
// Falls back to the generic dish placeholder for unmapped meals.
const MEAL_IMAGE_MAP = {
  "jollof rice": "/images/jollof.webp",
  "egusi soup": "/images/swallow_egusi.png",
  "pounded yam": "/images/swallow_egusi.png",
  suya: "/images/beef_suya.png",
  "fried plantain (dodo)": "/images/plantain.jpg",
  "ogbono soup": "/images/ogbona.png",
  "efo riro": "/images/egusi.jpg",
  "fried rice": "/images/jollof_fish_plantains.png",
  akara: "/images/pap-and-akara.webp",
  "moi moi": "/images/moimoi-and-custard.jpg",
  "pepper soup": "/images/fisherman_soup.png",
  "banga soup": "/images/fisherman_soup.png",
  "tuwo shinkafa": "/images/swallow_egusi.png",
  amala: "/images/Amala_ewedu_and_assorted_meat.jpg",
  "ewa agoyin": "/images/plantain.jpg",
  asun: "/images/beef_suya.png",
  "okra soup": "/images/okra.jpg",
  "ofada rice": "/images/ofada-and-ponmo.jpg",
  "meat pie": "/images/puffpuff.png",
  "puff puff": "/images/puffpuff.png",
  "yam porridge": "/images/fried-yam-and-egg-sauce.jpg",
  "chin chin": "/images/puffpuff.png",
  boli: "/images/boiled-plantain.jpg",
  "fish stew": "/images/fisherman_soup.png",
  "chicken stew": "/images/rice-and-stew.jpg",
  "beef stew": "/images/rice-and-stew.jpg",
  "vegetable soup": "/images/vegetable.svg",
  "edikang ikong": "/images/egusi.jpg",
  "afang soup": "/images/egusi.jpg",
  "bitterleaf soup": "/images/egusi.jpg",
  "oha soup": "/images/egusi.jpg",
  "groundnut soup": "/images/swallow_egusi.png",
  "peppered snails": "/images/beef_suya.png",
  "scotch egg": "/images/bread_scrambled_egg.jpg",
  "egg roll": "/images/bread_scrambled_egg.jpg",
  "fried yam": "/images/fried-yam-and-egg-sauce.jpg",
  "roasted corn": "/images/plantain.jpg",
  "boiled corn": "/images/plantain.jpg",
  "plantain chips": "/images/plantain.jpg",
  "egg sauce": "/images/bread_scrambled_egg.jpg",
  "bread and fried egg": "/images/bread_scrambled_egg.jpg",
  semovita: "/images/swallow_egusi.png",
  "wheat flour swallow": "/images/swallow_egusi.png",
  garri: "/images/garri-and-groundnut.jpg",
  fufu: "/images/swallow_egusi.png",
  eba: "/images/swallow_egusi.png",
  "coconut rice": "/images/jollof.webp",
  "beans and plantain": "/images/plantain.jpg",
  "porridge beans": "/images/plantain.jpg",
  "spaghetti jollof": "/images/jollof_fish_plantains.png",
  indomie: "/images/indomie-and-eggs.jpg",
  "yam and egg sauce": "/images/fried-yam-and-egg-sauce.jpg",
  "akara and bread": "/images/pap-and-akara.webp",
  "tea and bread": "/images/tea-bread-small-image.png",
  "custard and akara": "/images/moimoi-and-custard.jpg",
  "pap (ogi)": "/images/pap-and-akara.webp",
  "fried titus fish": "/images/fisherman_soup.png",
  "grilled catfish": "/images/fisherman_soup.png",
  "cowleg pepper soup": "/images/fisherman_soup.png",
  "goat meat pepper soup": "/images/fisherman_soup.png",
  "chicken pepper soup": "/images/fisherman_soup.png",
  nkwobi: "/images/beef_suya.png",
  "isi ewu": "/images/beef_suya.png",
  abacha: "/images/garri-and-groundnut.jpg",
  ugba: "/images/garri-and-groundnut.jpg",
  okpa: "/images/moimoi-and-custard.jpg",
  "tuwo masara": "/images/swallow_egusi.png",
  "miyan kuka": "/images/swallow_egusi.png",
  "miyan tuwo": "/images/swallow_egusi.png",
  kilishi: "/images/beef_suya.png",
  "pasta carbonara": "/images/indomie-and-eggs.jpg",
  "pizza margherita": "/images/puffpuff.png",
  "beef burger": "/images/ribeye.png",
  "caesar salad": "/images/vegetable.svg",
  "sushi roll": "/images/fisherman_soup.png",
  "chicken curry": "/images/rice-and-stew.jpg",
  tacos: "/images/beef_suya.png",
  "grilled salmon": "/images/fisherman_soup.png",
  "vegetable stir-fry": "/images/vegetable.svg",
  pancakes: "/images/pancakes-and-coffee.jpg",
  "french toast": "/images/bread_scrambled_egg.jpg",
  "mashed potatoes": "/images/fried-yam-and-egg-sauce.jpg",
  "greek salad": "/images/vegetable.svg",
  lasagna: "/images/indomie-and-eggs.jpg",
  "chicken wings": "/images/grilled-chicken-and-chips.jpg",
  "fish and chips": "/images/grilled-chicken-and-chips.jpg",
  ramen: "/images/indomie-and-eggs.jpg",
  burrito: "/images/rice-and-stew.jpg",
  "fried rice (chinese)": "/images/jollof_fish_plantains.png",
  omelette: "/images/bread_scrambled_egg.jpg",
  sandwich: "/images/tea-bread-small-image.png",
  "chili con carne": "/images/beef_suya.png",
  "pad thai": "/images/indomie-and-eggs.jpg",
  falafel: "/images/pap-and-akara.webp",
  hummus: "/images/vegetable.svg",
  tiramisu: "/images/pancakes-and-coffee.jpg",
  brownies: "/images/pancakes-and-coffee.jpg",
  "apple pie": "/images/pancakes-and-coffee.jpg",
  "fruit smoothie": "/images/vegetable.svg",
  "steak and fries": "/images/ribeye.png",
};

/**
 * Returns the public image path for a given meal name.
 * Looks up by lower-cased name; falls back to generic dish placeholder.
 */
export function getMealImage(mealName) {
  if (!mealName) return "/images/dish.webp";
  return MEAL_IMAGE_MAP[mealName.toLowerCase()] ?? "/images/dish.webp";
}

export default function transformTimetable(apiData) {
  const grouped = {};

  const items = apiData.items || apiData.data?.items || [];

  for (const item of items) {
    const { day_of_week, meal_slot, meal } = item;

    if (!grouped[day_of_week]) {
      grouped[day_of_week] = {
        day: day_of_week,
        color: DAY_COLORS[day_of_week] ?? "bg-green-800",
        meals: [],
      };
    }

    grouped[day_of_week].meals.push({
      id: item.id,
      mealId: meal.id,
      slug: meal.name.toLowerCase().replace(/\s+/g, "-"),
      type: meal_slot.toUpperCase(),
      name: meal.name,
      ingredients: meal.ingredients || [],
      price: `₦${Number(meal.price_min).toLocaleString()} - ₦${Number(meal.price_max).toLocaleString()}`,
      icon: SLOT_ICONS[meal_slot] ?? (
        <UtensilsIcon className="text-text-primary" />
      ),
      image: meal.image_url || getMealImage(meal.name),
    });
  }

  // preserve day order
  const ORDER = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ];
  return ORDER.filter((d) => grouped[d]).map((d) => grouped[d]);
}

// import {
//   BurgerIcon,
//   CoffeeIcon,
//   ForkAndKnife,
//   SnackIcon,
//   SpagIcon,
//   UtensilsIcon,
// } from "./icons";

// export const WeekPlan = [
//   {
//     day: "Sunday",
//     color: "bg-green-800",
//     meals: [
//       {
//         slug: "bread-and-egg",
//         type: "BREAKFAST",
//         name: "Bread & Egg",
//         description: "Soft bread served with lightly fried eggs.",
//         ingredients: ["Bread", "Egg", "Vegetable Oil", "Salt"],
//         price: "₦700",
//         icon: <SnackIcon className="text-text-primary" />,
//         image: "/images/bread_scrambled_egg.jpg",
//         category: ["Proteins"],
//       },
//       {
//         slug: "jollof-rice-and-grilled-fish",
//         type: "LUNCH",
//         name: "Jollof Rice & Grilled Fish",
//         description: "Smoky jollof rice paired with seasoned grilled fish.",
//         ingredients: [
//           "Rice",
//           "Tomatoes",
//           "Pepper",
//           "Onions",
//           "Fish",
//           "Vegetable Oil",
//           "Seasoning Cubes",
//           "Tomato Paste",
//           "Curry Powder",
//           "Thyme",
//           "Salt",
//         ],
//         price: "₦1,600",
//         icon: <BurgerIcon className="text-accent-orange" />,
//         image: "/images/jollof_fish_plantains.png",
//         category: ["Rice Dishes", "Proteins"],
//       },
//       {
//         slug: "garri-and-groundnut",
//         type: "DINNER",
//         name: "Garri & Groundnut",
//         description: "Simple soaked garri served with crunchy groundnuts.",
//         ingredients: ["Garri", "Groundnut", "Sugar", "Water"],
//         price: "₦400",
//         icon: <ForkAndKnife className="text-text-primary" />,
//         image: "/images/garri-and-groundnut.jpg",
//         category: ["Swallows"],
//       },
//     ],
//   },

//   {
//     day: "Monday",
//     color: "bg-orange-800",
//     meals: [
//       {
//         slug: "toast-and-tea",
//         type: "BREAKFAST",
//         name: "Toast & Tea",
//         description: "Buttered toast with warm sweet tea.",
//         ingredients: ["Bread", "Tea Leaves", "Sugar", "Milk", "Butter"],
//         price: "₦600",
//         icon: <CoffeeIcon className="text-text-primary" />,
//         image: "/images/tea-bread-small-image.png",
//         category: ["Proteins"],
//       },
//       {
//         slug: "beans-and-fried-plantain",
//         type: "LUNCH",
//         name: "Beans & Fried Plantain",
//         description: "Hearty beans served with sweet fried plantains.",
//         ingredients: ["Beans", "Plantain", "Palm Oil", "Salt", "Onions", "Pepper"],
//         price: "₦900",
//         icon: <BurgerIcon className="text-accent-orange" />,
//         image: "/images/plantain.jpg",
//         category: ["Proteins"],
//       },
//       {
//         slug: "indomie-and-egg",
//         type: "DINNER",
//         name: "Indomie & Egg",
//         description: "Quick noodles tossed with scrambled eggs.",
//         ingredients: ["Instant Noodles", "Egg", "Onions", "Vegetable Oil"],
//         price: "₦700",
//         icon: <SpagIcon className="text-text-primary" />,
//         image: "/images/indomie-and-eggs.jpg",
//         category: ["Proteins"],
//       },
//     ],
//   },

//   {
//     day: "Tuesday",
//     color: "bg-green-900",
//     meals: [
//       {
//         slug: "pap-and-akara",
//         type: "BREAKFAST",
//         name: "Pap & Akara",
//         description: "Smooth pap served with crispy bean cakes.",
//         ingredients: ["Corn Flour", "Beans", "Palm Oil", "Onions", "Pepper", "Salt", "Sugar", "Milk"],
//         price: "₦700",
//         icon: <SnackIcon className="text-text-primary" />,
//         image: "/images/pap-and-akara.webp",
//         category: ["Swallows", "Proteins"],
//       },
//       {
//         slug: "simple-beef-suya-and-bread",
//         type: "LUNCH",
//         name: "Beef Suya & Bread",
//         description: "Spiced grilled beef suya served with fresh bread.",
//         ingredients: ["Beef", "Suya Spice", "Bread", "Onions"],
//         price: "₦1,100",
//         icon: <UtensilsIcon className="text-accent-orange" />,
//         image: "/images/beef_suya.png",
//         category: ["Proteins"],
//       },
//       {
//         slug: "rice-and-stew",
//         type: "DINNER",
//         name: "Rice & Stew",
//         description: "Classic rice served with rich tomato stew.",
//         ingredients: [
//           "Rice",
//           "Tomatoes",
//           "Pepper",
//           "Onions",
//           "Vegetable Oil",
//           "Seasoning Cubes",
//           "Beef",
//           "Tomato Paste",
//           "Salt",
//         ],
//         price: "₦650",
//         icon: <ForkAndKnife className="text-text-primary" />,
//         image: "/images/rice-and-stew.jpg",
//         category: ["Rice Dishes"],
//       },
//     ],
//   },

//   {
//     day: "Wednesday",
//     color: "bg-green-800",
//     meals: [
//       {
//         slug: "bread-and-tea",
//         type: "BREAKFAST",
//         name: "Bread & Tea",
//         description: "Light breakfast of bread and warm tea.",
//         ingredients: ["Bread", "Tea Leaves", "Sugar", "Milk", "Butter"],
//         price: "₦500",
//         icon: <CoffeeIcon className="text-text-primary" />,
//         image: "/images/tea-bread-small-image.png",
//         category: ["Proteins"],
//       },
//       {
//         slug: "egusi-and-pounded-yam",
//         type: "LUNCH",
//         name: "Egusi & Pounded Yam",
//         description: "Rich melon soup served with soft pounded yam.",
//         ingredients: [
//           "Melon Seeds",
//           "Yam",
//           "Spinach",
//           "Palm Oil",
//           "Crayfish",
//           "Pepper",
//           "Onions",
//           "Seasoning Cubes",
//           "Salt",
//           "Beef",
//         ],
//         price: "₦1,400",
//         icon: <UtensilsIcon className="text-accent-orange" />,
//         image: "/images/swallow_egusi.png",
//         category: ["Swallows", "Soups"],
//       },
//       {
//         slug: "fried-yam-and-egg-sauce",
//         type: "DINNER",
//         name: "Fried Yam & Egg Sauce",
//         description: "Crispy fried yam served with spicy egg sauce.",
//         ingredients: [
//           "Yam",
//           "Egg",
//           "Tomatoes",
//           "Pepper",
//           "Onions",
//           "Vegetable Oil",
//           "Salt",
//         ],
//         price: "₦900",
//         icon: <ForkAndKnife className="text-text-primary" />,
//         image: "/images/fried-yam-and-egg-sauce.jpg",
//         category: ["Proteins"],
//       },
//     ],
//   },

//   {
//     day: "Thursday",
//     color: "bg-orange-900",
//     meals: [
//       {
//         slug: "moi-moi-and-custard",
//         type: "BREAKFAST",
//         name: "Moi Moi & Custard",
//         description: "Steamed bean pudding served with sweet custard.",
//         ingredients: ["Beans", "Corn Flour", "Sugar", "Milk", "Palm Oil", "Onions", "Pepper", "Crayfish", "Salt"],
//         price: "₦800",
//         icon: <SnackIcon className="text-text-primary" />,
//         image: "/images/moimoi-and-custard.jpg",
//         category: ["Proteins"],
//       },
//       {
//         slug: "amala-and-ewedu",
//         type: "LUNCH",
//         name: "Amala & Ewedu",
//         description: "Soft amala served with jute leaf soup.",
//         ingredients: [
//           "Yam Flour",
//           "Jute Leaves",
//           "Locust Beans",
//           "Crayfish",
//           "Pepper",
//           "Beef",
//           "Seasoning Cubes",
//           "Salt",
//         ],
//         price: "₦1,500",
//         icon: <UtensilsIcon className="text-accent-orange" />,
//         image: "/images/Amala_ewedu_and_assorted_meat.jpg",
//         category: ["Swallows", "Soups"],
//       },
//       {
//         slug: "grilled-chicken-and-fries",
//         type: "DINNER",
//         name: "Grilled Chicken & Fries",
//         description: "Grilled chicken served with crispy potato fries.",
//         ingredients: ["Chicken", "Potatoes", "Vegetable Oil", "Spices", "Salt", "Onions", "Pepper"],
//         price: "₦1,800",
//         icon: <BurgerIcon className="text-text-primary" />,
//         image: "/images/grilled-chicken-and-chips.jpg",
//         category: ["Proteins"],
//       },
//     ],
//   },

//   {
//     day: "Friday",
//     color: "bg-green-700",
//     meals: [
//       {
//         slug: "akara-and-ogi",
//         type: "BREAKFAST",
//         name: "Akara & Ogi",
//         description: "Crispy bean cakes served with smooth pap.",
//         ingredients: ["Beans", "Corn Flour", "Palm Oil", "Sugar", "Onions", "Pepper", "Salt", "Milk"],
//         price: "₦600",
//         icon: <SnackIcon className="text-text-primary" />,
//         image: "/images/pap-and-akara.webp",
//         category: ["Proteins"],
//       },
//       {
//         slug: "eba-and-okra-soup",
//         type: "LUNCH",
//         name: "Eba & Okra Soup",
//         description: "Cassava swallow served with okra soup.",
//         ingredients: [
//           "Cassava Flour",
//           "Okra",
//           "Palm Oil",
//           "Crayfish",
//           "Fish",
//           "Pepper",
//           "Salt",
//           "Seasoning Cubes",
//           "Locust Beans",
//           "Beef",
//         ],
//         price: "₦1,300",
//         icon: <UtensilsIcon className="text-accent-orange" />,
//         image: "/images/okra.jpg",
//         category: ["Swallows", "Soups"],
//       },
//       {
//         slug: "suya-and-cold-zobo",
//         type: "DINNER",
//         name: "Suya & Zobo",
//         description: "Spiced beef suya served with chilled hibiscus drink.",
//         ingredients: [
//           "Beef",
//           "Suya Spice",
//           "Hibiscus Leaves",
//           "Ginger",
//           "Sugar",
//         ],
//         price: "₦1,200",
//         icon: <ForkAndKnife className="text-text-primary" />,
//         image: "/images/beef_suya.png",
//         category: ["Proteins"],
//       },
//     ],
//   },

//   {
//     day: "Saturday",
//     color: "bg-orange-700",
//     meals: [
//       {
//         slug: "pancakes-and-coffee",
//         type: "BREAKFAST",
//         name: "Pancakes & Coffee",
//         description: "Fluffy pancakes served with hot coffee.",
//         ingredients: [
//           "Flour",
//           "Egg",
//           "Milk",
//           "Sugar",
//           "Butter",
//           "Coffee Beans",
//           "Baking Powder",
//           "Salt",
//         ],
//         price: "₦1,000",
//         icon: <CoffeeIcon className="text-text-primary" />,
//         image: "/images/pancakes-and-coffee.jpg",
//         category: ["Proteins"],
//       },
//       {
//         slug: "native-rice-and-ponmo",
//         type: "LUNCH",
//         name: "Native Rice & Ponmo",
//         description: "Local rice cooked with cow skin and spices.",
//         ingredients: [
//           "Rice",
//           "Cow Skin",
//           "Palm Oil",
//           "Pepper",
//           "Onions",
//           "Seasoning Cubes",
//           "Locust Beans",
//           "Crayfish",
//           "Salt",
//         ],
//         price: "₦1,100",
//         icon: <BurgerIcon className="text-accent-orange" />,
//         image: "/images/ofada-and-ponmo.jpg",
//         category: ["Rice Dishes", "Proteins"],
//       },
//       {
//         slug: "fish-pepper-soup",
//         type: "DINNER",
//         name: "Fish Pepper Soup",
//         description: "Light spicy fish soup with aromatic herbs.",
//         ingredients: ["Fish", "Pepper", "Ginger", "Garlic", "Scent Leaves", "Seasoning Cubes", "Salt", "Onions"],
//         price: "₦1,500",
//         icon: <SpagIcon className="text-text-primary" />,
//         image: "/images/fisherman_soup.png",
//         category: ["Soups", "Proteins"],
//       },
//     ],
//   },
// ];
